### PR TITLE
fix: show pdf file on website

### LINKED ISSUE #97: Bug: download book link goes to 404
### Describe the bug

The download book link in the footer takes you to a 404

image

### Steps to reproduce

1. Go to https://docs.opensauced.pizza
2. Click Download book
3. See 404

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by a0m0rajab**
## Description

This PR changes the PDF file location to assets to use it in the browser and show it, previously the pdf were showing on the local machine but not working on the browser. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #97

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by a0m0rajab** [comment]
I was expecting it to work... can we check if the file is created in the assets folder?

**Comment by bdougie** [comment]
> I was expecting it to work... can we check if the file is created in the assets folder?

You can workflows manually on your fork to confirm. https://www.youtube.com/watch?v=zOswqcXpQ54

**Comment by BekahHW** [comment]
@a0m0rajab have you been able to test this?

**Comment by a0m0rajab** [comment]
@BekahHW yes, it worked locally! 
sorry for the late reply.

**Comment by CBID2** [comment]
> @BekahHW yes, it worked locally! sorry for the late reply.

There's some conflicts that need to be solved on your branch @a0m0rajab

**Comment by a0m0rajab** [comment]
@CBID2 resolved.

**Comment by CBID2** [comment]
@bdougie, this needs review

**Review by CBID2 — APPROVED** [review]
Looks good to me! :)

**Comment by CBID2** [comment]
@a0m0rajab, we merged some new PRs, so can you solve the merge conflicts on your branch?

**Comment by CBID2** [comment]
Hey @a0m0rajab. Are you still working on this?

**Comment by BekahHW** [comment]
@a0m0rajab I'm still not able to get this working locally. 

image

**Comment by a0m0rajab** [comment]
@BekahHW How did you run this locally? for me, I just went through the docs and it worked without any further modification.

**Comment by BekahHW** [comment]
@a0m0rajab I ran `npm ci` and `npm start`.

**Comment by BekahHW** [comment]
Since we weren't able to get this consistently working, I removed it from the footer. I'm going to close this issue for now because we're about to merge in a PR that uses an updated version of docusaurus, so it would probably be easier to start over. But feel free to reopen.

**Pull request closed without merging**
