### PR TITLE
fix: Rearrange sections

### LINKED ISSUE #104: docs: Rearrange some sections
The content looks good, I am not everything is place in the correct sections for discoverability. 

Today the Contributing and Technical Guide overlap a lot, and the "Welcome page" now includes a highlight, but after considering, it should be separate. 

New layout

Start Here
- Introduction
- Highlights
- Insights
- Collaborations (Soon)
- FAQs

Community 
- ...that list here

Contributing Guide
- combine the technical and contributing list

I can clean this up after this is merged unless you have time this weekend @CBID2. I am going to be waiting in an airport for awhile and have time.

_Originally posted by @bdougie in https://github.com/open-sauced/docs/issues/103#issuecomment-1596189355_

### PR DESCRIPTION
**Pull request by CBID2**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR rearranges the layout of the sections. 
## Related Tickets & Documents

Fixes #104 
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [X] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
improve

### CODE REVIEW

**Comment by BekahHW** [comment]
@CBID2, I think that "Start Here" needs to be added as part of the PR, with the subcategories mentioned in the issue nested under there. 

So `start.js` would need to be added to the top of `sidebars.js`.

So it would look something like

```
  {
          type: 'category',
          label: 'Start Here!',
          collapsed: false,
          items: [
            'start/faqs',
            'start/highlights'
          ],
        },
    ```

**Comment by CBID2** [comment]
> @CBID2, I think that "Start Here" needs to be added as part of the PR, with the subcategories mentioned in the issue nested under there. 
> 
> 
> 
> So `start.js` would need to be added to the top of `sidebars.js`.
> 
> 
> 
> So it would look something like
> 
> 
> 
> ```
> 
>   {
> 
>           type: 'category',
> 
>           label: 'Start Here!',
> 
>           collapsed: false,
> 
>           items: [
> 
>             'start/faqs',
> 
>             'start/highlights'
> 
>           ],
> 
>         },
> 
>     ```

Ah ok

**Comment by CBID2** [comment]
> @CBID2, I think that "Start Here" needs to be added as part of the PR, with the subcategories mentioned in the issue nested under there.
> 
> So `start.js` would need to be added to the top of `sidebars.js`.
> 
> So it would look something like
> 
> ```
>   {
>           type: 'category',
>           label: 'Start Here!',
>           collapsed: false,
>           items: [
>             'start/faqs',
>             'start/highlights'
>           ],
>         },
>     ```
> ```

I think I got it @BekahHW! :)

**Comment by CBID2** [comment]
> @CBID2 checking in on this and how things are going. 

Hey @bdougie! :) @BekahHW, gave some advice. I think I got it this time

**Comment by bdougie** [comment]
Cherry picked and picked up over here #118

**Pull request closed without merging**
