### PR TITLE
docs: add Community Maintainers Guidelines

### LINKED ISSUE #242: Docs: Add OpenSauced Community Maintainers Guidelines
### Type of feature

🍕 Feature

### Current behavior

We have an "OpenSauced Maintainers Guide" containing information for people interested in becoming maintainers. But we also need guidelines about the expectations and responsibilities of maintainers, particularly Community Maintainers, to be on the same page in maintaining the repositories.

### Suggested solution

Add an "OpenSauced Community Maintainers Guidelines" with details as follow:

In the `contributing` folder inside `docs`:

- [ ] Create a subfolder called `opensauced-maintainers-guide`.
- [ ] Create a `community-maintainers-guide.md` and add the guidelines content here.
- [ ] Move `maintainers-guide.md` into the new folder.
- [ ] Update the `sidebars.js`.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR adds Community Maintainers Guideline with changes as follow:

In the `contributing` folder inside `docs`:

- [x] Create a subfolder called `opensauced-maintainers-guide`.
- [x] Create a `community-maintainers-guide.md` and add the guidelines content here.
- [x] Move `maintainers-guide.md` into the new folder.
- [x] Update the `sidebars.js`.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #242 

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

hell yeah GIF

### CODE REVIEW

**Comment by adiati98** [comment]
@BekahHW I adjusted some wording, so I need your review for all and please let me know if I need to fix anything. Thank you!

**Comment by BekahHW** [comment]
@adiati98 what does this mean - Issues outside the `good first issue` can be assigned **max. 2 times per contributor**. Suggest they check other repositories for more issues.

**Comment by adiati98** [comment]
@BekahHW after worked on this, I have these ideas:

- Change the title and sidebar_label in the `maintainers-guide.md` from "OpenSauced Maintainers Guide" to "Becoming OpenSauced Maintainer". Because most content in this page are information about how to become OpenSauced maintainer.
   https://github.com/open-sauced/docs/blob/943d2e41f9bf6bcab1e484303c9736c787ed9ff6/docs/contributing/maintainers-guide.md?plain=1#L3-L4
- Remove the "Committing and Merging Changes" section in the `maintainers-guide.md` because this is not necessary here. It's already covered in the "Community Maintainers Guidelines".
   https://github.com/open-sauced/docs/blob/943d2e41f9bf6bcab1e484303c9736c787ed9ff6/docs/contributing/maintainers-guide.md?plain=1#L47-L52
- Looking at the chapters, maybe we can change the title of "Contributing Guide" to "OpenSauced Guide" or "OpenSauced Guidelines"?

   opensauced contributing guide

**Review by BekahHW — APPROVED** [review]
@adiati98 this is good to go once the clarification is made

**Comment by adiati98** [comment]
> @adiati98 what does this mean - Issues outside the `good first issue` can be assigned **max. 2 times per contributor**. Suggest they check other repositories for more issues.

Issues that are not `good first issue` can only be assigned max. 2 times per contributor in the community repos. And we can suggest to other repos for more issues. I refer to your reply [here](https://docs.google.com/document/d/1y4DkR6b6Ln4KDjZToa0FkrsD3nn6SRrW5Du_xJvsDW8/edit?disco=AAABDy0H8OM). Or maybe I get it wrong? 😅

**Comment by adiati98** [comment]
> > > @adiati98 what does this mean - Issues outside the `good first issue` can be assigned **max. 2 times per contributor**. Suggest they check other repositories for more issues.
> > 
> > 
> > @BekahHW Issues that are not `good first issue` can only be assigned max. 2 times per contributor in the community repos. And we can suggest to other repos for more issues. I refer to your reply [here](https://docs.google.com/document/d/1y4DkR6b6Ln4KDjZToa0FkrsD3nn6SRrW5Du_xJvsDW8/edit?disco=AAABDy0H8OM). Or maybe I get it wrong? 😅
> 
> Ah, ok. People can take on more than two issues but not at a time. So, for example if they have an issue in guestbook and one in intro, they can't have one in pizza-verse.
> 
> My biggest concern is that contributors ask to take on issues across repos and don't finish them. I want them to contribute. But I want them to complete them.
> 
> So maybe more like:
> 
> Issues outside the `good first issue` can be assigned **max. 2 times per contributor** at a time. We love contributions, but we want to equip contributors to succeed by giving them time to complete issues. Through experience, we've found that two issues at a time allows them to focus on completing the issue and supports maintainers by not having issues open for long periods of time.

I update the wording as per your suggestion.
One last thing, should I change the file name as what you mentioned earlier from `community-maintainers-guide.md` to `community-maintainers.md`?

Once it confirmed, I can fix it and let you know or you can merge this PR.

**Pull request merged**
