### PR TITLE
Feature: Move project utilities to the docs folder

### PR DESCRIPTION
**Pull request by Susmita-Dey**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR moves project utilities to the docs folder.

## Related Tickets & Documents

Fixes issue [#166](https://github.com/open-sauced/ai/issues/166)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

No

## [optional] What gif best describes this PR or how it makes you feel?
image

### CODE REVIEW

**Comment by diivi** [comment]
Hey @Susmita-Dey, maybe the instructions were a bit unclear, but we wanted to remove this section entirely from the docs repo and into the docs folder in open-sauced/ai.

**Comment by Susmita-Dey** [comment]
Hey @diivi Shall I delete the folder of project-utilities from here?

**Comment by Susmita-Dey** [comment]
I have moved the file via this [PR](https://github.com/open-sauced/ai/pull/201)

**Comment by Susmita-Dey** [comment]
Deleted project utilities directory

**Review by bdougie — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
