### PR TITLE
feat: add Connections feature page

### LINKED ISSUE #190: Feature: connections feature
### Type of feature

🍕 Feature

### Current behavior

Currently not included in documentation.

### Suggested solution

Show how to use the connections feature, provide context for the value. Something like:
> The Connections feature serves as a networking hub for the open-source community. Whether you're seeking mentorship,  trying to grow your project or network, find opportunities to collaborate or work together, or want to learn more about what others are working on, this feature offers a streamlined way to connect.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR adds an explainer page about the connections feature, helping current and potential product users gain a better understanding of why it will aid them in their open source journey

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #190 
## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
No, but I would need a screenshot of the feature.

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @BekahHW. I placed my PR in draft for now because I'm debating on whether I should take a screenshot of the feature myself or do like we did with the Dev Card Explainer feature, wait for you to send me a link to the screenshot.

**Comment by bdougie** [comment]
@CBID2 curious if you got context and background on this feature. My guess is the current copy is placeholder. Let me know if that is a correct assumption.

[design context](https://app.campsite.design/opensauced/posts/qnglow1qb865)

**Comment by CBID2** [comment]
> @CBID2 curious if you got context and background on this feature. My guess is the current copy is placeholder. Let me know if that is a correct assumption.
> 
> [design context](https://app.campsite.design/opensauced/posts/qnglow1qb865)

I have a strong feeling that's the one @bdougie

**Comment by bdougie** [comment]
> Is this a premium feature?

Yes. You will need a coupon or pro plan.

**Comment by CBID2** [comment]
> > Is this a premium feature?
> 
> Yes. You will need a coupon or pro plan.

Ahh, I figured @bdougie. I'll add that to the explanation.

**Pull request merged**
