### PR TITLE
fix: items array in OpenSauced Maintainers Guides sidebar

### LINKED ISSUE #242: Docs: Add OpenSauced Community Maintainers Guidelines
### Type of feature

🍕 Feature

### Current behavior

We have an "OpenSauced Maintainers Guide" containing information for people interested in becoming maintainers. But we also need guidelines about the expectations and responsibilities of maintainers, particularly Community Maintainers, to be on the same page in maintaining the repositories.

### Suggested solution

Add an "OpenSauced Community Maintainers Guidelines" with details as follow:

In the `contributing` folder inside `docs`:

- [ ] Create a subfolder called `opensauced-maintainers-guide`.
- [ ] Create a `community-maintainers-guide.md` and add the guidelines content here.
- [ ] Move `maintainers-guide.md` into the new folder.
- [ ] Update the `sidebars.js`.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR fixes the items array in OpenSauced Maintainers Guides that caused build failed in #243 that is reverted in #244.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #242 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

cross fingers gif

### CODE REVIEW

**Comment by CBID2** [comment]
Success! 😊

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by adiati98** [comment]
@BekahHW the alternative solution also caused build failed with the same link error message. I'm not sure what's going on here.

There are two other alternatives to try:
1. Take both `community-maintainers-guide.md` and `maintainers-guide.md` files out from the `opensauced-maintainers-guide` folder and make them independent chapters.
2. Based on [line 43 on build error log](https://github.com/open-sauced/docs/actions/runs/7769325722/job/21188284365#step:6:44) and [this issue](https://github.com/facebook/docusaurus/issues/3136), we can use [`onBrokenLinks`](https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks) to lower the security if needed. But I'm not sure about links that build from the sidebar.

Just let me know if you want me to try any of those.

---

Hey @jdwilkin4, can you help me take a look at this PR? Some info here:

- This PR is an attempt to fix build failed. The first one was #243. Both have same error message of `Error: Docusaurus found broken links!`.
- Looking at the error as in screenshot below, somehow the `/contributing/opensauced-maintainers-guide/maintainers-guide/` links to all independent files and resolved as `/contributing/opensauced-maintainers-guide/contributing/<id>/`. All the independent files outside the `opensauced-maintainers-guide` folder look like be treated as part of the folder. 

   build failed
- Other alternatives that I can think of now is as what I mentioned to Bekah on top. Maybe you have other ideas?

**Comment by jdwilkin4** [comment]
Hey @adiati98 ! 

I was able to do a local build and replicate the error.

I went to the page that the error is referening here
http://localhost:3000/contributing/opensauced-maintainers-guide/maintainers-guide/

When you run the app locally, there are three links on that page that lead to a 404
Screenshot 2024-02-04 at 8 45 03 PM


You need to update the paths to be the following

```md
- [Triage issues](../triage-guide.md#triage-process) and bug reports.
```

```md
- adhere to our [Code of Conduct](../code-of-conduct.md) and be an example for treating contributors with respect,
```

```md
1. For commit and pull request standards, please refer to the [introduction to contributing](../introduction-to-contributing.md).
```
Then you will see that those links now go to the correct pages

Now you should be able to do another local build and test the production site locally and it should run now

Screenshot 2024-02-04 at 8 48 08 PM


Hope that helps 👍

**Pull request merged**
