### PR TITLE
feat: adds glossary to OpenSauced's getting started

### PR DESCRIPTION
**Pull request by Lymah123**
## Description

- This PR is a submission to the issue #200 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @Lymah123. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

**Comment by Lymah123** [comment]
Hi @CBID2 , can I close the PR? I have tried the solutions in the blog, but nothing works. Though I have updated my branch,

**Comment by Lymah123** [comment]
Screenshot (1366)

Hi, @CBID2 and @BekahHW. Check the screenshot. Do you think I can resolve the conflicts on my end?

**Comment by CBID2** [comment]
> Screenshot (1366)
> 
> Hi, @CBID2 and @BekahHW. Check the screenshot. Do you think I can resolve the conflicts on my end?

Yeah  you can @Lymah123. Look at the link I posted in the previous message to help you.

**Comment by BekahHW** [comment]
I had a PR merged in last week that's probably causing the conflicts. You'll need to update your branch with the latest changes.

**Pull request closed without merging**
